name: Main
on:
  push:
    branches: [ master ]
    
env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Preflight
      uses: SpectralOps/setup-preflight-action@v1
      with:
        preflight-version: "1.1.4"
    - name: Install and run Spectral CI
      uses: spectralops/spectral-github-action@v3
      with:
        spectral-dsn: ${{ env.SPECTRAL_DSN }}
        spectral-args: scan --ok --engines secrets,iac,oss --include-tags base,audit,iac --sarif
    - uses: actions/upload-artifact@v4
      with:
        name: spectral-report
        path: output.sarif
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: output.sarif    
